env: dev

catalog: workspace

schemas:
  bronze: bronze_dev
  silver: silver_dev
  gold: gold_dev

paths:
  raw: /Volumes/case/default/case_data/sources/
  bronze: bronze_dev
  silver: silver_dev
  gold: gold_dev

execution:
  load_mode: full
  process_date: "2026-06-26"
